services:
  - type: web
    name: ocr-pesee-webhook
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MISTRAL_API_KEY
        sync: false
      - key: ODOO_URL
        sync: false
      - key: ODOO_DB
        sync: false
      - key: ODOO_USER
        sync: false
      - key: ODOO_PASSWORD
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
